FROM node:22-alpine

ARG PNPM_STORE_PATH=/root/.local/share/pnpm/store

RUN corepack enable && corepack install -g pnpm@10.26.2
RUN pnpm config set store-dir ${PNPM_STORE_PATH}

WORKDIR /app

COPY frontend ./frontend

RUN sh -c "cd /app/frontend && pnpm install --frozen-lockfile && pnpm run build"

EXPOSE 3000

CMD ["sh", "-c", "cd /app/frontend && pnpm run start"]

